In [1]:
import numpy as np

In [5]:
x = np.dstack(
    [   [
            [1,2],
            [4,5]
        ],
        [
            [7,8],
            [0,1]
        ],
        [
            [3,1],
            [2,5]
        ]
    ]
)
print(x)
print(x.shape)

[[[1 7 3]
  [2 8 1]]

 [[4 0 2]
  [5 1 5]]]
(2, 2, 3)


In [19]:
x*x

array([[[ 1, 49,  9],
        [ 4, 64,  1]],

       [[16,  0,  4],
        [25,  1, 25]]])

In [14]:
xt = np.transpose(x, (0,2,1))
print(xt)
print(xt.shape)

[[[1 2]
  [7 8]
  [3 1]]

 [[4 5]
  [0 1]
  [2 5]]]
(2, 3, 2)


In [17]:
xx = x@xt
print(xx)
print(x.shape)

[[[59 61]
  [61 69]]

 [[20 30]
  [30 51]]]
(2, 2, 3)
